### ISSUE TITLE
MSn data?

### ISSUE THREAD

**Issue by niekdejonge** [mzmine/biohack23_p15#10]
Do we want to be able to upload only MS2 data. Or should MSn or MS1 also be possible?
I have no experience with working with MSn data and matchms is not able to handle this type of data, so implementing this would be a lot more complicated.

I know you did do a study on MSn data @robinschmid, is this your main use case, or could we start with an implementation for MS2 and maybe later add MSn functionality?

**Comment by florian-huber** [comment]
I agree, that this is more than a quick fix somewhere in matchms. But it makes sense to consider adding MSn support to `matchms` I believe (see issue there --> https://github.com/matchms/matchms/issues/550).

**Comment by niekdejonge** [comment]
This will be further discussed in issues of matchms.
