### ISSUE TITLE
Which database do we upload to? 

### ISSUE THREAD

**Issue by niekdejonge** [mzmine/biohack23_p15#3]
The tool should result in automatic uploading to common libraries. 
We could directly upload to GNPS and Massive for instance. 

Uploading directly to these existing libraries would have as downside that these libraries will get mixed with libraries that previously did not have quality control. How should we address this? 

One thing I could think of is adding to the metadata, which quality checks were performed. This would allow users of public libraries to filter out spectra that were not checked by quality control.

**Comment by robinschmid** [comment]
Personally database would be far down stream. All the databases are managed quite manually. You usually still need to push the change and request a review etc. Automating this might not be necessary and stable as things will change in the future. 

I think the keyword here is data formats and conversion to allow people to add libraries to all databases.

**Comment by robinschmid** [comment]
We are building a repository though were people just upload the metadata files that should then be cleaned up and enriched. We have a template for this metadata and can then rerun the automatic library generation with different parameters, generating libraries for different purposes:
- machine learning
- library matching
- ...

**Comment by niekdejonge** [comment]
We have actually just implemented exactly this functionality in matchms in the last few months. So it would be very interesting to collaborate further on this. Might still be valuable to have this directly implemented in MZMine/Java as well, but it is good to know that all this is already available in matchms. So it might be interesting to try to connect the two and/or to share our experience to make it easier for you to add similar metadata cleaning functionality into MZMine.

**Comment by justinjjvanderhooft** [comment]
Exactly, let's prevent re-inventing the wheel :-)
